### PR TITLE
Multiple changes

### LINKED ISSUE #6: Disable buttons and clearing tenant ID when searchbar is empty

### PR DESCRIPTION
**Pull request by TargetCrafter**
- Fixed the buttons staying enabled when no customer was selected
- Moved clear button into searchbox
- Added titles to all buttons
- Updated Teams and Defender logo
- Renamed Compliance to Purview
- Resized buttons and searchbox to prepare for multi column layout

### CODE REVIEW

**Review by Nathanymous — COMMENTED** [review]
I approve on all changes except the defender logo change.
I cant figure out if the new or the old logo (uploaded in the repo) is the logo that Microsoft uses. If the newly uploaded logo is indeed the new logo Microsoft uses, and if i can get that confirmed i approve.
The rest of the changes looks good.

**Comment by TargetCrafter** [comment]
Microsoft has no official logo for Microsoft 365 Defender, only a line icon in the admin center.
Because I want all the logos to be in the fluent design style I took the windows defender logo and added space between the sections just like the line icon in admin center.

**Comment by Nathanymous** [comment]
There is a official logo with lines in the middle, you can search it up.
However, I think we should try and stick to the official logo's, most of the logo's we use are official. The defender logo we had was just perfectly fine. I think we should stick to that logo.

**Comment by TargetCrafter** [comment]
I reverted to the old defender logo we used before. There is not really a definite logo for Microsoft 365 Defender.

**Review by Nathanymous — APPROVED** [review]
After the reverted change this is all good.
Ready to merge

**Pull request merged**
