### PR TITLE
Included the domain in search

### LINKED ISSUE #21: Expand search to include primarydomainname field
Expand on the existing search function to include the primarydomainname field in the results so that you can also find a tenant if you only know the domain instead of the tenant name.

### PR DESCRIPTION
**Pull request by TargetCrafter**
I added the the primary domain names to the customers datalist so that you can search for the domain if you don't know the tenant name.

Search display:
image

### CODE REVIEW

**Review by Nathanymous — CHANGES_REQUESTED** [review]
Tested this, but didn't find it working. I couldn't import my files anymore, thus couldn't import customers.

**Comment by TargetCrafter** [comment]
It works for me, can you try to run "localStorage.clear()" in the console, refreshing and trying again?

**Comment by Nathanymous** [comment]
Went on and tested this again:
- Tested this with a webserver hosted from vscode (npx http-server)
- Wasn't able to upload a .csv file in Firefox
- Tested on Microsoft Edge, and still wasn't able to upload a .csv file
- I tested this all on another PC then the last time I tested this.
- When doing "localStorage.clear()" in Edge i get the error "undefined"

@TargetCrafter is there something wrong with my testing setup, or can you look if there is something wrong in the code?

**Review by Nathanymous — APPROVED** [review]
Tested this again on another laptop with a http server, and it now all works as intended.
This can be merged.

**Pull request merged**
