### PR TITLE
added: PIM button

### PR DESCRIPTION
**Pull request by harshleey**
after-pim-button

### CODE REVIEW

**Comment by TargetCrafter** [comment]
Can you change the name in the button to "Azure PIM"? I think that is a more appropriate name for it. Also, can you use the icons used in the Entra portal? The icon you used now doesn't seem to be a fluent design icon.
I would also prefer to have a maximum of 2 columns, 1 for the portals (existing buttons) on 1 for direct links like this one and others in the future.

**Review by TargetCrafter — CHANGES_REQUESTED** [review]
Can you change the name in the button to "Azure PIM"? I think that is a more appropriate name for it. Also, can you use the icons used in the Entra portal? The icon you used now doesn't seem to be a fluent design icon.
I would also prefer to have a maximum of 2 columns, 1 for the portals (existing buttons) on 1 for direct links like this one and others in the future.

**Comment by harshleey** [comment]
Alright. Will work on that.

**Comment by harshleey** [comment]
Hello Johan,

I can't seem to find the Entra portal you mentioned, that's what's
delaying my push.

**Comment by TargetCrafter** [comment]
Wonuola,

The URL for PIM requests is https://entra.microsoft.com/#view/Microsoft_Azure_PIMCommon/ActivationMenuBlade
It uses the "Person Lock" icons from [fluenticons](https://fluenticons.co/outlined).
I also pushed a few changes since you created your fork which contains the layout ready for the second column. You can just add a button. You might want to pull this to make sure everything works correctly.
Keep in mind that this button is customer-independant, so msp-button will not work as it gets disabled when no customer is selected.

**Comment by TargetCrafter** [comment]
Wonuola,

I had a look at your pr, but there were some alignment issues, and the button was disabled when no customer was selected, so not as intended. I have since pushed the change myself, so I will close this pr now.
I needed to have this function to be implemented, but if you want to add more functions, feel free to create a pr.

**Pull request closed without merging**
