### PR TITLE
Added drag to import functionality

### LINKED ISSUE #22: Support drag-and-drop import
I would be nice if we could import csv and mspcsv files by dragging them into the app.

### PR DESCRIPTION
**Pull request by TargetCrafter**
Add the option to drag a csv or mspcsv file into the app to import its content. By doing this i also fixed an issue where the file wouldn't get correctly imported sometimes.

Dropzone when hovering file over app:
image

### CODE REVIEW

**Review by Nathanymous — CHANGES_REQUESTED** [review]
The drag and drop worked, but after this there was no delete button in the searchbar anymore when i selected a customer.

**Comment by TargetCrafter** [comment]
The delete is visible for me, but keep in mind that this only shows up when you have text in the searchbox.
image

**Comment by Nathanymous** [comment]
Went on and tested this again:

- Tested this with a webserver hosted from vscode (npx http-server)
- Wasn't able to upload a .csv file in Firefox
- Tested on Microsoft Edge, and still wasn't able to upload a .csv file
- I tested this all on another PC then the last time I tested this.
- When doing "localStorage.clear()" in Edge i get the error "undefined"

The above is for the problem that the import doesn't work anymore. Also found 2 extra issues:

- When opening the webpage there is an upload logo in the top left of the screen. Maybe some CSS which is incorrect?
afbeelding

- When dragging a .csv file, I get multiple errors in the console, and the drag and drop animation is not displayed on the screen.
afbeelding

**Review by Nathanymous — APPROVED** [review]
Tested this again on another laptop with a http server and now it all works as intended,
When the MSP Manager is opened with inspector open the drag and drop animation is not good aligned, but this will be fixed in a later fix.

**Pull request merged**
